### PR TITLE
created route for fetching all users

### PR DESCRIPTION
**Pull request by Evil-star25**
## WHY
closes https://github.com/PkFokam-Alumni-Network/CommunityBackendService/issues/33

## WHAT

created route to fetch all users 

## TESTING
Pytest

<!Screenshot 2024-12-16 210637

### CODE REVIEW

**Comment by bjoelfra** [comment]
Overall, everything seems fine to me, except the little remarks I made @atakoutene @Renwarren

**Comment by bjoelfra** [comment]
Your what says you created user login and tested but I think it should be; implemented a function to fetch all users.  For testing try to specify what you used; pytest, postman.....

**Review by atakoutene — APPROVED** [review]
Except the small comments from @bjoelfra , I fixed already, I think everything is all good!!

**Comment by Renwarren** [comment]
In the future, while a test is good, we should also provide screenshots from postman because we are building endpoints.
cc @bjoelfra @Evil-star25 @atakoutene 

Good work @Evil-star25 . Keep up 👍 🚀

**Pull request merged**
